version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXT_PUBLIC_APP_URL=http://localhost:4000
      # - NEXT_PUBLIC_NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_SECRET=development-secret-key-change-in-production
      - PORT=3000
    ports:
      - '4000:3000'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
