import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getAppName } from "@/lib/app-config"; // Renamed from @/lib/config
import type { AppName } from "../AppConfig"; // Updated import path
import { AppConfigProvider } from "@/components/AppConfigProvider";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const appName: AppName = await getAppName();

  return (
    <html lang="en" data-app-name={appName ?? undefined}>
      <head></head>
      <body className={inter.className}>
        <nav className="w-full flex gap-4 p-4 border-b bg-gray-50 mb-6">
          <Link href="/" className="font-semibold hover:underline">
            Home
          </Link>
          <Link href="/todos" className="font-semibold hover:underline">
            Todos
          </Link>
        </nav>
        <AppConfigProvider>{children}</AppConfigProvider>
      </body>
    </html>
  );
}
