import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { RequestAppConfig } from "@/middleware"; // Corrected to use @/ alias

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers(); // Await the headers
  const configHeader = headerList.get("X-Request-Config");
  let appConfig: RequestAppConfig | null = null;
  if (configHeader) {
    try {
      appConfig = JSON.parse(configHeader);
    } catch (error) {
      console.error(
        "Failed to parse X-Request-Config header in RootLayout:",
        error
      );
    }
  }

  // The appConfig (including origin) is now primarily passed to pages/components
  // via props if needed for SSR. The script tag is a fallback or for pure client-side needs.

  return (
    <html lang="en">
      <head>
        {appConfig && (
          <script
            id="__APP_CONFIG__"
            type="application/json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify(appConfig), // Still useful for client-side only components
            }}
          />
        )}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
