import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getRequestConfig } from "@/lib/config";
import type { AppConfig } from "../AppConfig.type"; // Removed .ts
import { AppConfigProvider } from "@/components/AppConfigProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const appConfig: AppConfig | null = await getRequestConfig();
  const setupNameForClient = appConfig?.name;

  const htmlAttributes: { [key: string]: string | undefined } = { lang: "en" };
  if (setupNameForClient) {
    htmlAttributes["data-setup-name"] = setupNameForClient;
  }

  return (
    <html {...htmlAttributes}>
      <head>{/* Script tag for __APP_SETUP_NAME__ removed */}</head>
      <body className={inter.className}>
        <AppConfigProvider>{children}</AppConfigProvider>
      </body>
    </html>
  );
}
